### ISSUE TITLE
Cannot add email on macOS

### ISSUE THREAD

**Issue by Ishan95014** [leinelissen/aeon#343] opened 2022-07-07 20:19 UTC
On Intel macOS Monterey, clicking "Add new Gmail account" in Email Account settings just closes the dialog box with no further information. 

Swiping to missing control becomes very slow and laggy to and from aeon until the app is closed. 

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/59368580/177864202-dd5ee5da-1102-4c37-a406-8df95fe64470.png">

**Comment by leinelissen** [comment] 2022-07-12 08:19
Hey @Ishan95014! Thanks for noticing the issue and reaching out. I've had a look at the problem and I managed to reproduce it. The problem was due to a configuration error in the build pipeline. The issue has been resolved as of v0.2.20 which has just been released. The build pipeline is now running and the new version should be available via the auto-updater or the regular download page in the coming half hour. Can you please let me know if the update resolves your issue so that I can close the issue! Much appreciated.

**Comment by Ishan95014** [comment] 2022-07-12 13:52
I'm not sure how to trigger the auto-updater, and there is no Mac version in the latest release section. Should I just wait for it to update ?

**Comment by leinelissen** [comment] 2022-07-14 14:58
Okay the macOS versions have now been compiled and uploaded as well. It should start immediately downloading the update next time you start the application.

**Comment by Ishan95014** [comment] 2022-07-14 15:20
<img width="661" alt="image" src="https://user-images.githubusercontent.com/59368580/179017630-44774b52-dea3-46c0-b6e1-4b0a2db95d93.png">
Are you planning on verifying the app with them ?

**Comment by leinelissen** [comment] 2022-07-18 09:16
Yes, I am currently working on getting the documentation together. Until then, I am afraid this message will be displayed.

**Closed by leinelissen** 2022-07-18 09:16 UTC
Labels: bug
